// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zafqhxmagriuhnjqkakp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InphZnFoeG1hZ3JpdWhuanFrYWtwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0ODYzMDcsImV4cCI6MjA3NDA2MjMwN30.J6mQt9ywspXR4EcJS0_VL69D-WTV4UCDvAGWtVBp5m4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});